/*CREATE TABLE USUARIOS
(ID INT PRIMARY KEY IDENTITY(1,1),
NOME VARCHAR(100) NOT NULL,
SENHA VARCHAR(20) NOT NULL,
FUNCAO VARCHAR(20) NOT NULL,
MATRIZ VARCHAR(20) NOT NULL,
FILIAL VARCHAR(20) NOT NULL)*/


SELECT * FROM USUARIOS

INSERT INTO USUARIOS (NOME, SENHA, FUNCAO, MATRIZ, FILIAL) VALUES
('Charles Pereira','123','Administrador','1','1')

